baseURL: "https://rahulmysore23.github.io/"
title: Presence on internet
paginate: 5
theme: PaperMod
publishDir: docs

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

module:
  mounts:
    - source: "static"
      target: "static"
    - source: "images"
      target: "static/images"

params:
  env: production 
  title: Rahul Mysore
  description: "Software Engineer with 5 years of experience building backends. Currently pursuing a masters degree."
  keywords: [ Blog, Portfolio, PaperMod ]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: [ "<link or path of image for opengraph, twitter-cards>" ]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Rahul Mysore
    subtitle: "Software Engineer with 5 years of experience building backends. Currently pursuing a masters degree."
    imageUrl: "/images/mine.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: image
    buttons:
      - name: Posts
        url: posts
      - name: About
        url: about

  # home-info mode
  homeInfoParams:
    Title: "Hi there 👋"
    Content: Welcome to my blog

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/rahulmysore23"
    - name: github
      url: "https://github.com/rahulmysore23"
    - name: youtube
      url: "https://www.youtube.com/@rahulmysore23"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: about
      name: about
      url: /about/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
taxonomies:
  category: categories
  tag: tags
